# -*- coding: utf-8 -*-
"""transformers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pU-pLcCVi5DYex8wdprfOPUK_m-uayUW
"""

from sklearn.base import BaseEstimator, TransformerMixin
import pandas as pd

class MedianTransformer(BaseEstimator, TransformerMixin):
    """Custom transformer to fill missing values with column medians"""
    def fit(self, X, y=None):
        self.medians_ = X.median()
        return self

    def transform(self, X):
        return X.fillna(self.medians_)